- name: Install required packages
  apt:
    name:
      - net-tools
      - iputils-ping
    state: present

- name: Configure bastion host
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
  notify:
    - Restart SSH

- name: Allow bastion host to ping service nodes
  ufw:
    default: deny
    rule: allow
    proto: icmp

- handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted
```

**ansible/roles/haproxy/tasks/main.yaml**:

```yaml
- name: Install HAProxy
  apt:
    name: haproxy
    state: present

- name: Copy HAProxy configuration
  copy:
    src: haproxy.conf
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - Restart HAProxy

- handlers:
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted
```

**ansible/roles/keepalived/tasks/main.yaml**:

```yaml
- name: Install Keepalived
  apt:
    name: keepalived
    state: present

- name: Copy Keepalived configuration
  copy:
    src: keepalived.conf
    dest: /etc/keepalived/keepalived.conf
  notify:
    - Restart Keepalived

- handlers:
    - name: Restart Keepalived
      service:
        name: keepalived
        state: restarted
```

**ansible/roles/monitoring/tasks/main.yaml**:

```yaml
- name: Install Telegraf, InfluxDB, and Grafana
  apt:
    name:
      - telegraf
      - influxdb
      - grafana
    state: present

- name: Configure Telegraf
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  notify:
    - Restart Telegraf

- name: Configure InfluxDB
  template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
  notify:
    - Restart InfluxDB

- handlers:
    - name: Restart Telegraf
      service:
        name: telegraf
        state: restarted

    - name: Restart InfluxDB
      service:


